### ISSUE TITLE
Use Vuexfire for Realtime DB and Firestore simultaneously

### ISSUE THREAD

**Issue by tw00** [posva/vuexfire#203] opened 2018-11-19 17:33 UTC
There are many use cases where you have a project, that relies on both Firebase Realtime DB and Firestore, since both Databases have their advantages and disadvantages (see [official docs](https://firebase.google.com/docs/firestore/firestore-for-rtdb)).

It would be very nice, if you could use vuexfire in both cases simultaneously in the same project. Currently this is not possible since both packages ```vuexfire``` and ```vuexfire@next``` are essentially the same npm package. Furthermore the enhacers (```firebaseAction```, ```firebaseMutations```) and probably also the  global mutations prefixed by vuexfire/ use the same name.

Apparently somebody started to work on a "namespaced" version:
https://github.com/vuexfirestore/vuexfirestore

Not sure if this is an "official" version. Are there any plans to create an independen package?

**Comment by posva** [comment] 2018-11-19 17:59
Duplicate of https://github.com/vuejs/vuefire/issues/188
(code is now shared between vuefire and vuexfire)

**Closed by posva** 2018-11-19 17:59 UTC

**Comment by posva** [comment] 2018-11-19 18:01
> Apparently somebody started to work on a "namespaced" version:
https://github.com/vuexfirestore/vuexfirestore


Does it? I don't see what is new there 🤔

**Comment by tw00** [comment] 2018-11-19 20:12
@posva Ops sorry, didn't see that somebody already created an issue. Thanks for the clarification.

> Does it? I don't see what is new there 🤔

Me neither except for an updated README...

**Comment by posva** [comment] 2018-11-19 20:53
It's difficult to search in another repository haha

it only adds a function but it doesn't seem to actually have the code for it. Other than that, it's the same readme
